import { expect, test } from './fixtures'

test('bulk replacement previews the real PDF, applies atomically, reports fidelity and undoes in one step', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Try a sample PDF/ }).click()
  await page.getByRole('button', { name: 'Find text', exact: true }).click()
  await page.getByRole('button', { name: 'Find and replace', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Find and replace' })
  await dialog.getByLabel('Text to find').fill('the')
  await dialog.getByLabel('Replacement text').fill('our')
  await dialog.getByLabel('Whole words', { exact: true }).check()
  const count = await dialog.locator('.replace-matches > label').count()
  expect(count).toBeGreaterThan(1)
  await dialog.getByRole('button', { name: 'Preview replacements' }).click()
  await expect(dialog.locator('.pdf-page')).toHaveAttribute('aria-busy', 'false')
  await page.screenshot({ path: testInfo.outputPath('replacement-review.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: `Apply ${count} replacements` }).click()
  await expect(dialog).toHaveCount(0)
  await page.keyboard.press('ControlOrMeta+k')
  await page.getByRole('combobox', { name: 'Find a command' }).fill('Review edit fidelity')
  await page.getByRole('combobox', { name: 'Find a command' }).press('Enter')
  const report = page.getByRole('dialog', { name: 'Edit fidelity report' })
  await expect(report.locator('.fidelity-list article')).toHaveCount(count)
  await report.getByRole('button', { name: 'Close fidelity report' }).click()
  const undo = page.getByRole('button', { name: 'Undo', exact: true })
  await undo.click()
  await expect(undo).toBeDisabled()
  await expect(page.locator('.status-bar')).toContainText('0 text edits')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.locator('.status-bar')).toContainText(`${count} text edits`)
})
